name: wonderbird

services:
  wonderbird:
    image: pthoelken/wonderbird:latest
    container_name: wonderbird
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      # CUSTOM_USER: "user"
      # PASSWORD: "ChangeMe"
    ports:
      - "3000:3000"
    volumes:
      - wonderbird:/config
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  wonderbird:
